version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password    # Senha do root do MySQL
      MYSQL_DATABASE: monitoring_db        # Nome do banco de dados a ser criado
      MYSQL_USER: admin                    # Nome do usuário
      MYSQL_PASSWORD: admin                # Senha do usuário
    ports:
      - "3306:3306"  # Porta do MySQL
    volumes:
      - mysql-data:/var/lib/mysql  # Volume persistente para os dados
      - ./mysql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Script de inicialização

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - mysql

volumes:
  grafana-data:
  mysql-data:
